export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

export const EMAIL_ENTERED = 'EMAIL_ENTERED';
export const PASSWORD_ENTERED = 'PASSWORD_ENTERED';
export const USERNAME_ENTERED = 'USERNAME_ENTERED';

export const SIGN_UP_START = 'SIGNIN_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
